### ISSUE TITLE
引用块中插入图片, 导出后可能会使标题消失

### ISSUE THREAD

**Issue by lisslulay** [MadMaxChow/VLOOK#86]
in typora
![image](https://user-images.githubusercontent.com/78423568/141310374-bbf4e509-5751-4a45-a92c-cdf1c1a6f57f.png)

export
![image](https://user-images.githubusercontent.com/78423568/141310312-615986be-8c03-4681-9cdb-2ea175545a4b.png)

**Comment by MadMaxChow** [comment]
谢谢反馈，能把 Markdown 的源文件内容发一下吗？也可以发邮件 maxchow@qq.com

**Comment by lisslulay** [comment]
源文件：[引用块中标题显示问题.md](https://github.com/MadMaxChow/VLOOK/files/7574455/default.md)

![image](https://user-images.githubusercontent.com/78423568/142724695-31d8a01f-a56b-45c1-acfe-3cb1e965596d.png)

**Comment by MadMaxChow** [comment]
谢谢您的反馈！
大概看了一下代码，应该是对默认图片的题注处理问题，这块代码比较旧，有些细节没有及时调整过来，后面版本会修复一下。
你如果急用的话，我可以发一个内测的版本给你。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MadMaxChow/VLOOK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MadMaxChow/VLOOK] 引用块中插入图片, 导出后可能会使标题消失 (Issue #86)





 
源文件：引用块中标题显示问题.md
 

 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lisslulay** [comment]
没事，我不急，辛苦你们了，维护开源代码很不容易的🌷🌷🌷

________________________________
发件人： MAX°孟兆 ***@***.***>
发送时间： 2021年11月22日星期一 17:24
收件人： MadMaxChow/VLOOK
抄送： Shanshan; Author
主题： Re: [MadMaxChow/VLOOK] 引用块中插入图片, 导出后可能会使标题消失 (Issue #86)


谢谢您的反馈！
大概看了一下代码，应该是对默认图片的题注处理问题，这块代码比较旧，有些细节没有及时调整过来，后面版本会修复一下。
你如果急用的话，我可以发一个内测的版本给你。


------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MadMaxChow/VLOOK" ***@***.***&gt;;
发送时间:&nbsp;2021年11月20日(星期六) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MadMaxChow/VLOOK] 引用块中插入图片, 导出后可能会使标题消失 (Issue #86)






源文件：引用块中标题显示问题.md



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
